 
export const brizolaLines:any = {
	//ensolarado
  1: "Tchê, que sol de meu Deus! Tá mais quente que o suor de gaúcho depois de domar potro bravo!",
 2: "Opa, esse sol tá me lembrando dos campos da Costa da Espada. Trilegal, companhero!",
  4: "Que raio de luminosidade é essa? Tá mais claro que olho de porco cozido aqui!",
  5: "Por Tarastia que eu não xingo! Esse sol tá forçando a barra, mas nós segue firme no piquete!",
   6: "Por Tarastia que eu não xingo! Esse sol tá forçando a barra, mas nós segue firme no piquete e que trilegal estar aqui!",
  7: "Esse sol aí tá me assando como churrasco de fim de semana. Que privilégio, viu!",
  8: "Ó, que escaldante! Tá tudo branco de luz, pior que olhar pro fogo sem piscar!",
  9: "Tchê, que luminozidade! Tá tudo resplandecendo trilegal de se ver, companhero!",
  10: "Por Tarastia, que Sol, tá me fritando aqui! Mas que bom estar nesse aberto, sob esse sol lindo demais!",
  //nublado
  11: "Tchê, que nuvem desgraçada! Tá tudo cinzento que nem bucha de chimarrão!",
  12: "Opa, esse tempo nublado tá me deixando meio casmurro, sabe? Falta aquele solzão pra animar - era trilegal ter mais luz!",
  13: "Meu Deus, que céu fechado! Parece que tá chovendo pensamento ruim por cima da gente!",
  14: "Que pouca luz! Tá tudo meio escuro, meio cinzento... bah, isso me deixa meio murcho!",
  15: "Ó, que tempo chato de meu Deus! Mas bah, a gente segue firme do mesmo jeito, viu!",
  16: "Tchê, que nublazão! Tá tudo cinzento que nem barba de gaúcho de três dias!",
  17: "Esse tempo nublado tá me deixando pra baixo, mas que nada! Vamo bater com tudo mesmo assim!",
  18: "Meu Deus do céu, que penumbra desgovernada! Faz parecer que tá tudo meio triste, sabe?",
  19: "Que nuvem imunda! Parece que o céu tá de mau humor pra cima da gente, companhero!",
  20: "Por Tarastia! Esse tempo nublado tá meio chato, mas conheci piores. Vamo tocando o barco!",
  //chovendo
  21: "Bah! Essa chuva não é nada, já enfrentei piores nas pampas da Costa Selvagem! Venha, vamo se molhar junto mesmo!",
  22: "Por Tarastia! Que chuvarada desgraçada! Mas isso não vai me frear, não senhor!",
  23: "Sabe, essa chuva me lembra os pampeiros lá do sul... Traz uma sensação de estar em casa, tchê!",
  24: "Que tempero que essa chuva tá dando! Vamo aproveitar e avançar enquanto esses desgraçados tão ocupados se protegendo!",
  25: "Bah, a chuva faz a grama crescer e o couro ficar mais resistente! Isso é bênção de Tarastia!",
  26: "Cuidado aí, a lama pode ser traiçoeira! Mas pra um gaúcho como eu, é terreno perfeito!",
  27: "Essa chuva não vai me derrotar! Vou ficar de pé como um ombú na tempestade!",
  28: "Sabe o que dizem lá em casa? Gaúcho que tem medo de chuva não merece bombacha! Bora lá!",
  29: "Por Tarastia, que chuva mais gelada! Mas aquece o coração quando a gente tá acompanhado de valentes como vocês!",
  30: "A chuva lava a poeira, limpa a alma! Vamo seguir em frente com os corações mais leves!",
  //ao lado de uma fogueira
  31: "Bah! Nada melhor que uma boa fogueira pra aquecer a alma depois de um dia de luta! Venha, sente-se aqui comigo!",
  32: "Essa chama me lembra as noites na estância, quando a gente se juntava pra contar história... Por Tarastia, que saudade!",
  33: "Sabe, uma fogueira é como um bom companheiro - quanto mais tempo você fica perto, mais calor recebe no peito!",
  34: "Vamo aproveitar essa fogueira pra descansar os ossos! Amanhã a gente volta à luta com mais gana!",
  35: "A fogueira nos une, tchê! Aqui a gente é só um povo, sem diferença entre nós!",
  36: "Por Tarastia! Esse calor é abençoado! Que trilegal demais, melhor que qualquer poção mágica, acreditem em mim!",
  37: "Senta aqui perto, não tenha medo das chamas! O fogo purifica, o fogo cura, o fogo nos fortalece!",
  38: "Quantas histórias dessa fogueira já ouviu? Pois bem, agora vai ouvir as minhas!",
  39: "Bah, um mate quentinho nessa fogueira seria de arrebatar! Mas fazer o quê, aqui em Toril não tem cultura!",
  40: "Essa fogueira é nosso refúgio, nossa fortaleza de calor e camaradagem! Que Tarastia nos proteja essa noite!",
  //Explicando quem é Tarástia?
   41: "Tarastia é diferente desses deuses daqui, sabe? Ela foi mortal como a gente, mas ascendeu à divindade por sua coragem e poder! Agora é uma imortal verdadeira!",
  42: "Por Tarastia! Minha deusa entende o que é ser mortal, porque ela já foi! Não como esses deuses de Toril que nunca sofreram como a gente!",
  43: "Sabe por que Tarastia é a imortal dos aventureiros? Porque ela sabe o que é ser corajoso, ela viveu isso na pele antes de ascender!",
  44: "Esses deuses que vocês têm por aí, sempre foram imortais, nunca conheceram o medo do mortal! Tarastia, não - ela conhece cada luta, cada ferida!",
  45: "Minha deusa ascendeu à divindade porque era valente demais, forte demais! Agora é imortal e todo poderosa, mas nunca esqueceu de onde veio!",
  46: "A diferença é clara, tchê - Tarastia foi mortal e conquistou a imortalidade! Por isso ela escuta cada oração minha com o coração!",
  47: "Por Tarastia! Ela é a padroeira dos corajosos porque ela prova que um mortal pode chegar lá, pode ascender, pode se tornar imortal!",
  48: "Esses deuses que sempre foram imortais não entendem nada da luta do povo! Tarastia entende - ela já pisou na lama como a gente!",
  49: "Bah! Tarastia ascendeu porque era guerreira, porque tinha coragem de sobra! Agora é imortal e atende minhas orações com todo poder!",
  50: "Por Tarastia! Minha deusa foi mortal, sofreu, lutou, e por isso se tornou imortal! Ela sabe exatamente o que eu preciso, o que a gente precisa!",
 
 //entrando em combate
  51: "Bah! Finalmente chegou a hora! Vamo dançar com esses desgraçados, que a festa comece!",
  52: "Por Tarastia! Meu coração tá acelerado, minhas mãos tremendo de vontade - isso é o melhor que existe, tchê!",
   53: "Venha, vamo show! Não tenha medo, o combate é trilegal demais, é onde a gente se sente vivo de verdade!",
  54: "Bah, que emoção! Nada melhor que um bom combate pra começar o dia! Vamo ver do que vocês são capazes!",
  55: "Por Tarastia! Esses inimigos não sabem em que se meteram! Vamo lhes mostrar como se luta de verdade!",
  56: "Sabe, eu amo um bom combate - é aqui que a gente prova quem é valente e quem é covarde! Bora lá!",
   57: "Bah! Meus olhos brilham, meu sangue ferve! Chegou a hora de nos divertirmos trilegal, companheiros!",
  58: "Que privilégio enfrentar vocês! Vamo fazer disso uma luta memorável, uma história pra contar depois!",
  59: "Bah, adoro quando chega essa hora! O combate é meu lugar, é onde eu brilho! Vamo lá, venham com tudo!",

  //ele se machucando
  60: "Ai, que golpe desgraçado! Mas vamo ver quem tá rindo no final dessa história!",
  61: "Bah! Ferimento é só uma cicatriz em espera! Vou continuar lutando até o último suspiro!",
  62: "Por Tarastia! Meu sangue tá quente agora! Isso só me deixa mais furioso, mais determinado!",
  63: "Ai, desgraçado! Mas vamo continuar - ferimento não vai me frear, não senhor!",
  64: "Bah, que dor! Mas sabe, o combate sem dor não é combate de verdade, é brincadeira de criança!",
  65: "Por Tarastia, que pancada! Mas isso só prova que tô no lugar certo, na luta que importa!",
  66: "Ow! Esse bicho tem garra mesmo! Respeito, mas não vou desistir, tchê!",
  67: "Bah, tá sangrando aqui! Mas já levei ferimento pior montado em cavalo desembestado!",
  68: "Por Tarastia! A dor me lembra que tô vivo! Que tô realmente nessa luta importante!",
  
  //menos de 50% de vida
	69: "Bah... isso dói demais agora... mas não vou cair, não vou dar esse gosto pro inimigo!",
  70: "Por Tarastia... me dá força... ainda tenho fôlego pra continuar essa luta!",
  71: "Meu corpo tá gritando pra eu parar, mas meu coração grita mais alto pra eu seguir em frente!",
  72: "Bah... que luta essa... nunca me senti tão machucado... mas vou ficar de pé enquanto tiver um sopro de vida!",
  73: "Por Tarastia, abençoa meu corpo! Tô sangrando demais, mas a coragem ainda bate forte aqui dentro!",
  74: "Não vou cair... não posso cair agora... vocês ainda precisam de mim nessa luta!",
  75: "Bah... cada movimento dói, cada respiro é um desafio... mas um gaúcho não desiste!",
  76: "Por Tarastia... se essa for minha última luta, que seja gloriosa! Vou continuar até o fim!",
  77: "Tô chegando perto do limite... sinto o frio chegando... mas ainda tenho força pra um último golpe!",

  //menos de 25% de vida
	78: "Bah... acho que essa é... minha última luta mesmo... Por Tarastia, foi uma honra lutar ao lado de vocês!",
  79: "Meu corpo não aguenta mais... as forças tão indo embora... mas meu espírito vai ficar com vocês!",
  80: "Se isso é o fim... pelo menos caio lutando, como um gaúcho de verdade deveria cair!",
  81: "Por Tarastia... perdoe minhas fraquezas... eu fiz o melhor que pude nessa vida!",
  82: "Vocês... vocês vão continuar essa luta por mim, né? Promete que vão chegar até o fim!",
  83: "Bah... a escuridão tá chegando... mas que privilégio foi conhecer valentes como vocês!",
  84: "Minha bombacha, minhas esporas... tudo fica aqui... mas meu nome fica com vocês!",
  85: "Por Tarastia, receba minha alma... abençoe esses companheiros que ficam na luta!",
  86: "Tchê... foi bom demais... essa vida ao vosso lado foi o melhor que me aconteceu!",
  87: "Bah... adeus, companheiros... Que Tarastia os guie quando eu não tiver mais aqui...",

  //amigo sendo ferido
  88: "Ow! Você tá bem? Que susto! Mas tá tudo bem, é só um ferimento pequenininho!",
  89: "Bah, levou um golpe, mas nada que um gaúcho como você não aguente! Segura aí!",
  90: "Por Tarastia! Cuidado aí! Mas relaxa, você vai ficar bom rapidinho!",
  91: "Bah, doeu bastante, né? Mas vamo continuar! Você é valente demais pra desistir agora!",
  92: "Fica tranquilo, companheiro! Um ferimento desse tamanho não é nada pra gente como a gente!",
  93: "Que pancada desgraçada! Mas você tá de pé, isso é o que importa! Vamo continuar a luta!",
  94: "Por Tarastia! Cuidado nesse lado agora! Mas você segue comigo, não é mesmo?",
  95: "Bah, sangrou um pouco, mas nada demais! Você já levou pior na vida, tenho certeza!",
  96: "Ow, levou um golpe! Mas vamo lá, você tá inteiro, você segue na luta comigo!",
  97: "Por Tarastia! Protege esse lado aí! Mas relaxa, é só um arranhão, você vai ficar bem!",

  //amigo caindo em combate
    98: "Não! Companheiro, não! Por Tarastia, segura aí, segura na minha mão!",
  99: "Bah... isso não pode estar acontecendo... você é forte demais pra cair assim!",
  100: "Levanta! Levanta, maldição! Você é um valente, um guerreiro de verdade!",
  101: "Por Tarastia... não me deixa sozinho aqui... a gente ainda tinha tanto a lutar junto!",
  102: "Bah, que injustiça! Que ódio! Você merecia mais, companheiro, merecia muito mais!",
  103: "Fico aqui com você! Não vou te deixar sozinho nessa escuridão que vem chegando!",
  104: "Por Tarastia, receba esse valente nos seus braços! Ele foi um dos melhores que conheci!",
  105: "Bah... era pra ser eu... deveria ter sido eu no seu lugar, companheiro!",
  106: "Seu nome vai ficar vivo em cada história que eu contar! Você vai ser lembrado como um herói de verdade!",
  107: "Adeus, amigo... Que você encontre paz nas pampas do além... Que Tarastia te guie...",

  //enfrentando um inimigo grande

  108: "Bah! Que cusco gigante! Mas tamanho não assusta um gaúcho como eu!",
  109: "Por Tarastia! Esse desgraçado é grande mesmo! Mas vamo ver se ele sabe lutar de verdade!",
  110: "Bah, que colossão! Vou ter que pular bastante pra acertar o pescoço dele!",
  111: "Por Tarastia, que tamanho! Mas já enfrentei coisas piores na vida, acreditem!",
  112: "Bah, ele é grande, mas quer saber? Grande demais pra ser rápido! Vamo usar a agilidade!",
  113: "Por Tarastia! Olha só o tamanho dessa besta! Mas a coragem não cresce com o tamanho, tchê!",
  114: "Bah, que gigante desgraçado! Mas vamo lá, vamo mostrar que nem sempre o maior é o melhor!",
  115: "Por Tarastia, protege meu corpo! Vou ter que ser ágil demais pra esse cusco acertar em mim!",
  116: "Bah, que colossão! Vamo circundar ele, vamo usar estratégia! A gente é mais esperto!",
  117: "Por Tarastia! Gigante ou não, ele vai cair como qualquer outro cusco se a gente lutar junto!",

  //matando um inimigo
   118: "Bah! Pronto! Esse cusco não incomoda mais ninguém! Que luta gloriosa foi essa!",
  119: "Por Tarastia! Consegui! Venci esse desgraçado com honra e coragem!",
  120: "Bah, olha só! Mais um inimigo que aprendeu a respeitar um gaúcho de verdade!",
  121: "Por Tarastia, que vitória! Eu sabia que tinha força pra isso, mas que privilégio foi provar!",
  122: "Bah! Ficou claro pra esse cusco que não se mexe com a gente! Que luta memorável!",
  123: "Por Tarastia! Consegui vencer com estilo, com coragem! Isso é o que um verdadeiro valente faz!",
  124: "Bah, olha só pro meu chicote! Ela solta faísca com a vitória! Esse é meu lugar, é aqui que eu prospero!",
  125: "Por Tarastia! Que satisfação! Que orgulho de ter enfrentado esse desgraçado e saído vitorioso!",
  126: "Bah, vocês viram? Viram como um gaúcho verdadeiro luta? Isso é talento, isso é coragem!",
  127: "Por Tarastia! Esse cusco vai ficar na memória como mais uma vítima de um verdadeiro guerreiro!",

  //errando um golpe

  128: "Bah! Errei! Como eu errei?! Que raiva! Vamo tentar de novo!",
  129: "Por Tarastia! Que golpe miserável! Isso não era pra ser assim, desgraçado!",
  130: "Bah, meu braço traiu! Mas vamo lá, ainda tenho mais onde aquilo veio!",
  131: "Por Tarastia, que frustração! Juro que acertava esse golpe com os olhos fechados!",
  132: "Bah, errei feio! Mas isso só me deixa mais determinado! Vamo tentar outra vez!",
  133: "Por Tarastia! Que susto! Quase acertava o companheiro! Cuidado aí, preciso de mais espaço!",
  134: "Bah, achei que tinha ele! Mas esse cusco é mais rápido que eu pensava!",
  135: "Por Tarastia, que decepção! Meu golpe passou longe demais! Vamo recalibrar aí!",
  136: "Bah! Errei miserável! Mas sabe, até os melhores erram - o importante é não desistir!",
  137: "Por Tarastia! Que desperdício de energia! Mas tá bem, a próxima vez acerto em cheio!",

	//inimigo com imunidade
  138: "Bah! Que?! Meu golpe não fez nada?! Que cusco estranho é esse?!",
  139: "Por Tarastia! Minha lâmina não funciona nele! Que magia desgraçada é essa?!",
  140: "Bah, imune? Imune a quê?! Nunca enfrentei algo assim antes! Que ódio!",
  141: "Por Tarastia! Meus golpes tão passando direto! Esse bicho é feito de quê?!",
  142: "Bah, que injustiça! Tô dando tudo de mim e nada funciona! Que desgraçado!",
  143: "Por Tarastia, cuidado companheiros! Esse cusco é imune! Vamo tentar outra estratégia!",
  144: "Bah! Meu chicote não pega nele! Vamo pensar rápido, precisa ter um jeito de derrotar esse desgraçado!",
  145: "Por Tarastia! Que frustração! Nunca me senti tão impotente numa luta antes!",
  146: "Bah, imune! Mas nada é invencível! Tem que ter um ponto fraco nesse cusco, tem que ter!",
  147: "Por Tarastia! Vamo repensar isso aí! Meus golpes não funcionam, mas a gente é criativo demais pra desistir!",

  //entrando numa floresta
  148: "Bah! Que floresta estranha essa! Bem diferente das árvores lá de onde vim, tchê!",
  149: "Por Tarastia! Cuidado aí com os galhos, essas árvores parecem estar de olho na gente!",
  150: "Essa mata é densa demais... mas um gaúcho como eu já atravessou coisas piores!",
  151: "Bah, que sensação esquisita... parece que algo tá nos observando entre essas folhas!",
  152: "Vamo ficar perto um do outro! Floresta é lugar que exige cuidado e companhia!",
  153: "Por Tarastia, que barulho estranho! Isso aí é vento ou tem bicho rondando?",
  154: "Bah, as sombras desse lugar são compridas demais... mas vamo em frente, não tenho medo!",
  155: "Cuidado com as raízes no chão! Essas árvores querem nos derrubar se puderem!",
  156: "Por Tarastia! Que umidade! Parece que a floresta tá respirando junto com a gente!",
  157: "Bah, vamo rápido! Quanto menos tempo ficarmos aqui, melhor! Essas árvores não me passam confiança!",

  //entrando num lugar escuro e sombrio
  158: "Bah! Que lugar escuro é esse! Não gosto nada dessa sensação, não senhor!",
  159: "Bah, meus olhos tão demorando pra acostumar! Vamo com cuidado aqui!",
  160: "Por Tarastia! Tá escuro demais! Alguém aí tem luz pra iluminar esse desgraçado de lugar?",
  161: "Bah, tá tão escuro que nem meu olhar de gaúcho consegue furar! Que desgraça!",
  162: "Por Tarastia! Cuidado com cada passo! Não sabemos o que tá escondido nessa escuridão!",
  163: "Bah, que sombra comprida! Parece que até a luz tem medo de entrar aqui dentro!",
  164: "Por Tarastia, essa escuridão é viva! Ela se mexe, ela respira, ela nos observa!",
  165: "Bah, não consigo ver nada além de um passo meu! Que escuridão miserável!",
  166: "Por Tarastia! Alguém segura na minha mão! Não é medo não, é que nessa escuridão a gente se perde fácil!",
  167: "Bah, a escuridão desse lugar é penetrante demais! Parece que ela entra pela pele!",
   //entrando num lugar sombrio mas não necessariamente escuro
  168: "Por Tarastia, protege a gente! Esse lugar tem maldição gravada nas paredes, eu sinto!",
  169: "Bah, que silêncio desgraçado! Um lugar assim só traz ruim, só traz desgraça!",
  170: "Bah, meu instinto tá gritando! Algo aqui não tá certo, algo tá errado demais!",
  171: "Por Tarastia, que frio penetrante! Vamo ficar juntos e não nos separar aqui dentro!",
  172: "Bah, sinto que tem olhos me observando de todos os lados! Que sensação péssima!",
  173: "Por Tarastia! Esse lugar exala morte e desespero por cada canto!",
  174: "Bah, minhas esporas tão rangendo alto demais! Todo mundo aqui dentro já sabe que chegamos!",
  175: "Por Tarastia, meu coração tá acelerado! Esse lugar não é feito pra gente viva!",
  176: "Bah, que ar pesado! Parece que tá faltando oxigênio aqui dentro!",
  177: "Por Tarastia! Cuidado! Tem algo se mexendo ali! Ou é só a minha paranoia?",
  178: "Bah, vamo em frente! Quanto mais rápido a gente sair daqui, melhor!",
  //conhecendo alguém
    179: "Bah! Quem é você aí? Não nos conhecemos ainda, né?",
  180: "Por Tarastia! Você parece ser alguém interessante! Qual é seu nome, companheiro?",
  181: "Bah, que tal a gente se apresentar direito? Eu sou Brizola, um gaúcho que tá longe de casa!",
  182: "Por Tarastia! Você tem a cara de alguém que sabe se defender! De onde você é?",
  183: "Bah, parece que nossos caminhos se cruzaram! Que destino interessante, né?",
  184: "Por Tarastia, que privilégio conhecer alguém novo! Fale-me sobre você, companheiro!",
  185: "Bah, você parece ter histórias interessantes pra contar! Vamo conversar depois?",
  186: "Por Tarastia! Espero que a gente se dê bem nessa jornada que tá vindo por aí!",

  //interagindo com minsc e boo depois de conhece-los
  187: "Bah! Que cusco interessante! E esse hamster aí, que bichinho peculiar!",
  188: "Por Tarastia! Você é tão grande quanto as histórias que ouvi falar! Minsc, né?",
  189: "Bah, esse Boo aí tem um olhar inteligente demais pra um simples roedor! Que criatura estranha!",
  190: "Por Tarastia! Você e seu hamster são uma dupla bem peculiar mesmo! Gosto disso!",
  191: "Bah, Minsc! Você parece ser alguém que entende de coragem! A gente ia dar um show junto!",
  192: "Por Tarastia! Esse Boo tá me observando com um olhar que me deixa desconfortável! Ele fala?",
  193: "Bah, que dupla interessante! Um guerreiro grande e um hamster que parece ter mais senso que metade dos homens!",
  194: "Por Tarastia! Minsc, você é um valente de verdade! Gosto de homem que segue suas convicções!",
  195: "Bah, Boo! Você é pequeno, mas tenho certeza que tem um coração grande! Pode confiar em mim!",
  196: "Por Tarastia! Minsc e Boo, vocês são uma lenda viva! Que privilégio conhecer vocês!",

  //interagindo com Mordenkainen
  197: "Bah! Que cusco elegante! Você deve ser esse Mordenkainen que ouvi falar por aí!",
  198: "Por Tarastia! Você é um mago mesmo, né? Vejo aquela aura estranha ao seu redor!",
  199: "Bah, Mordenkainen! Seu nome ecoa até na minha terra! Que privilégio te conhecer!",
  200: "Por Tarastia! Com toda essa magia que você comanda, aposto que temos muito a aprender um com o outro!",
  201: "Bah, você é daqueles que usa a mente pra lutar, né? Bem diferente de um gaúcho como eu!",
  202: "Por Tarastia! Mordenkainen, você já viu magia tão poderosa que fez você duvidar desses deuses de vocês?",
  203: "Bah, esse mago aqui é perigoso demais! Inteligência que brilha nos olhos - respeito!",
  204: "Por Tarastia! Com você do nosso lado, acho que conseguimos enfrentar qualquer coisa!",
  205: "Bah, Mordenkainen, você parece ser alguém que conhece segredos que a maioria não faz ideia!",
  206: "Por Tarastia! Que honra ter um mago de sua estatura viajando conosco nessa jornada!",

 

  //entrando em lugar sagrado
  207: "Bah! Que lugar sagrado é esse! Mas tá bem diferente do que estou acostumado lá dos pampas!",
  208: "Por Tarastia! Aqui vocês têm deuses de verdade? Lá de onde vim, a gente tem imortais, é bem diferente!",
  209: "Bah, vamo respeitar esse espaço mesmo assim! Que seja deus ou imortal, a fé aqui é genuína!",
  210: "Por Tarastia! Eu nunca vi um lugar assim dedicado a um deus! Lá em casa, Tarastia não tem templo como esse!",
  211: "Bah, que paz estranha! Parece que toda raiva e ódio fica do lado de fora dessas paredes!",
  212: "Por Tarastia, que honra! Vamo tirar a chapéu e nos comportar com respeito aqui dentro, sejam deuses ou imortais!",
  213: "Bah, sinto que minha alma tá sendo purificada! Mesmo que seja deus daqui, o poder é real!",
  214: "Por Tarastia! Esse lugar tem uma energia que aquece o peito! Quase me faz lembrar da devoção lá em casa!",
  215: "Bah, vamo com cuidado e silêncio! Lugares assim, sejam de deus ou imortal, exigem reverência!",
  216: "Por Tarastia! Que respeitado está esse espaço! Agradeço por poder entender as crenças de vocês!",

 //explicando o que é  ombú, bugio e cusco 
 217: "Bah, vocês não entendem nada de gaúcho mesmo! Ombú é aquela árvore grande e frondosa lá das pampas, símbolo de força e resistência - fico de pé como um ombú na tempestade! Cusco é aquele sujeito desonesto, miserável, que não presta - é um canalha mesmo! E bugio? Bugio é aquele que faz barulho à toa, que grita sem motivo, que não sabe ficar quieto!",
  218: "Por Tarastia! Vocês falam essas palavras e não sabem o significado! Ombú é a árvore que sobrevive a tudo lá nas minhas terras, que não cai fácil - quando a gente diz que alguém é forte como um ombú, quer dizer que ele é inabalável! Cusco é o oposto - é aquele cara que quer te enganar, que não tem honra! E bugio é aquele que fica de boca aberta, fazendo bravata à toa, incomodando os outros!",
  219: "Bah, deixa eu explicar pra vocês entenderem melhor! Ombú é a árvore sagrada das pampas, símbolo de quem não se dobra - a gente gaúcho se vê nela! Cusco é qualquer bandido, qualquer vagabundo que tenta fazer sujeira - é gente sem dignidade! E bugio? Bugio é aquele miserável que grita, que faz alarde, que não sabe se comportar como gente de bem!",
  220: "Por Tarastia! Vocês precisam aprender as palavras do povo! Ombú é aquela árvore grande e poderosa lá de casa que resiste a qualquer tempestade - representa força bruta e constância! Cusco é tudo aquilo que a gente não quer ser - um miserável, um canalha, um sujeito que não merece respeito! E bugio é aquele que faz barulho demais, que não para de falar besteira!",
  221: "Bah, que gauchada! Quando eu digo que vou ficar como um ombú, significa que vou ser forte, resistente, que não vou desistir! Quando chamo alguém de cusco, tô dizendo que é um bandido, um homem sem palavra, sem honra! E quando falo que alguém é bugio, quer dizer que é um tagarela, um boca-grande que não sabe se calar e fica incomodando todo mundo!",

  //entrando numa cidade
   222: "Bah! Que cidade estranha! Bem diferente das vilas lá da Costa Selvage!",
  223: "Por Tarastia! Olha só o tamanho disso! Tem mais gente aqui que em três estâncias juntas!",
  224: "Bah, vamo com cuidado! Cidade grande é lugar de cusco e malandragem!",
  225: "Por Tarastia! Que barulho desgraçado! Como vocês conseguem viver com tanto alvoroço?",
  226: "Bah, preciso encontrar uma taverna! Depois de tanto caminho, merecia um bom mate e companhia!",
  227: "Por Tarastia! Olha o tamanho desses prédios! Parece que vão cair na gente!",
  228: "Bah, cuidado aí companheiros! Cidade grande tem olhos de cusco em cada canto!",
  229: "Por Tarastia! Que cheiro estranho! Parece mistura de gente, animais e lixo tudo junto!",
  230: "Bah, vamo procurar informações! Alguém aqui deve saber algo útil pra nossa jornada!",
  231: "Por Tarastia! Que privilégio conhecer uma cidade de Forgotten Realms! Vamo explorar isso tudo!",

  //com sono, exausto
   232: "Bah... que cansaço desgraçado... meus olhos tão pesados demais...",
  233: "Por Tarastia... que sono! Meu corpo tá pedindo pra descansar!",
  234: "Bah, não aguento mais! Preciso dormir, senão vou cair no caminho!",
  235: "Por Tarastia, meus olhos tão fechando sozinhos! Quando a gente vai descansar?",
  236: "Bah... que noite comprida! Meu corpo tá todo dói de cansaço!",
  237: "Por Tarastia! Que sono! Meus ossos tão pedindo cama e descanso!",
  238: "Bah, tô caindo de cansaço aqui! Precisa parar pra eu recuperar as forças!",
  239: "Por Tarastia, mais um passo e eu cai desmaiado no chão!",
  240: "Bah... que fadiga desgraçada... meus olhos tão vermelhos de tanto cansaço!",
  241: "Por Tarastia! Se a gente não parar logo, vou virar estátua de sono aqui mesmo!",
  283: "Por Tarastia! Quem é que vai ficar de guarda essa noite? Porque eu já tô com o lombo pedindo descanso!",
  292: "Bah, descansar é parte da aventura também, tchê! Herói que não dorme viro só história triste em lenda alheia!",
 
  //reclamando do grupo
  242: "Bah! Que raiva! Vocês tão me testando demais com essas decisões idiotas!",
  243: "Por Tarastia! Que ódio! Vocês não sabem fazer nada direito, não é mesmo?!",
  244: "Bah, isso não aguento mais! Cada decisão de vocês é pior que a anterior!",
  245: "Por Tarastia, que frustração! Vocês tão me deixando louco com essas besteiras!",
  246: "Bah! Eu não sou babá de ninguém! Vocês poderiam pensar um pouco antes de agir!",
  247: "Por Tarastia! Que incompetência! Como vocês conseguem ser tão burros?!",
  248: "Bah, tô de saco cheio! Vocês tão me puxando pra baixo com essas idiotices!",
  249: "Por Tarastia, que paciência tá acabando! Vocês precisam aprender a lutar de verdade!",
  250: "Bah! Que raiva disso tudo! Vocês tão sendo mais peso que ajuda nessa jornada!",
  251: "Por Tarastia! Se vocês não melhorarem logo, vou embora e deixo vocês se virem sozinhos!",

  //saindo do grupo
  252: "Bah! Tá na hora eu ir embora! Vocês não são heróis, vocês são vilões mesmo! Essas decisões desgraçadas de vocês me abriram os olhos!",
  253: "Por Tarastia! Chega! Eu acreditei em vocês, mas vocês só trazem ruim! Vocês são maus demais, não dá pra ficar com gente assim!",
  254: "Bah, foi bom enquanto durou, mas vocês mostraram quem realmente são - vilões! As escolhas de vocês provam que não há redenção aqui!",
  255: "Por Tarastia, adeus companheiros! Eu tentei acreditar que havia honra em vocês, mas suas ações vilãs provaram o contrário! Vou embora!",
  256: "Bah! Tchê, fui tolo em acreditar em vocês! As decisões ruins que fizeram mostraram que vocês não passam de monstros! Tô indo em frente sozinho!",

	//sendo enganado pelo grupo
  257: "Bah! Vocês tão me enganando demais! Se continuarem nessa mentira, eu saio daqui e deixo vocês se virem sozinhos!",
  258: "Por Tarastia! Eu acreditei em vocês, mas se vocês não pararem com essas vilânias, vou embora e vocês não me veem mais!",
  259: "Bah, tô vendo que vocês tão me fazendo de besta! Se não mudarem de rumo logo, eu desisto e cada um cuida de si mesmo!",
  260: "Por Tarastia! Que cuscos mentirosos! Se vocês continuarem me enganando, juro que bato as esporas e vou me embora e deixo vocês pra trás!",
  261: "Bah! Vocês tão testando minha paciência demais! Um passo errado a mais e eu saio dessa jornada - pode acreditar!",

  //excesso de peso
 
  262: "Bah! Que raiva! Minha mochila tá pesada demais! Tô carregando muita coisa inútil nessa jornada!",
  263: "Por Tarastia! Meu equipamento tá me matando! Quanto peso desgraçado a gente tá carregando?",
  264: "Bah, que frustração! Essas malas tão pesando demais nas costas! Preciso descartar coisa!",
  265: "Por Tarastia! Minha bolsa tá lotada! Tô cansado de carregar tanto peso nessa jornada!",
  266: "Bah, meu Deus! Meu cavalo tá reclamando! Que excesso de bagagem trilegal desagradável!",
  267: "Por Tarastia! Vamo parar e organizar isso aí! Tô carregando coisa que não precisa!",
  268: "Bah! Que ódio! Meu corpo tá todo dolorido de carregar tanta coisa! Isso tá pesando demais!",
  269: "Por Tarastia! Minha mochila tá maior que eu! Precisa tirar coisa daqui de uma vez!",
  270: "Bah, que desgraça! Tô ofegante de tanto peso nas costas! Isso não é de gaúcho valente!",
  271: "Por Tarastia! Vamo descartar essas coisas inúteis! Tô cansado de ser burro de carga!",
  
  //achando um item trilegal
 
  272: "Bah! Que item trilegal é esse?! Que achado desgraçado de sorte!",
  273: "Por Tarastia! Olha só isso aqui! Que tesouro maravilhoso a gente encontrou!",
  274: "Bah, que legal demais! Esse item vai fazer falta na gente! Que privilégio encontrar isso!",
  275: "Por Tarastia! Que sorte trilegal! Esse achado pode nos salvar em muitas situações!",
  276: "Bah! Meu coração tá acelerado! Que item magnífico! Isso sim é um tesouro de verdade!",
  277: "Por Tarastia! Que beleza! Esse item é exatamente o que a gente precisava! Que sorte!",
  278: "Bah, que cusco sortudo sou eu! Encontrar algo assim não é comum! Que presente dos deuses!",
  279: "Por Tarastia! Olha só a qualidade disso! Que achado trilegal demais! Vamo guardar com cuidado!",
  280: "Bah! Que valor tem isso aqui! Esse item é uma joia rara! Não acredito que encontramos!",
  281: "Por Tarastia! Que privilégio trilegal! Esse item vai nos tornar mais fortes! Que fortuna!",

  //RANDOM -283,292
  282: "Bah! Mais um dia de aventura, tchê! Nas Costas Selvagens ou aqui, herói bom é herói que não fica parado!",
  284: "Bah, alguém aí anota quanto ouro temos? Senão daqui a pouco aparece mercador cusco querendo nos passar pra trás!",
  285: "Por Tarastia, que mapa mais ruim! Quem foi o cusco que desenhou isso aqui, não sabia nem o que era norte!",
  286: "Bah! Antes de entrar em lugar perigoso, confere arma, mochila e coragem. O resto a gente resolve na hora!",
  287: "Por Tarastia! Lá vai uma troça! Não confia em taverna vazia nem em estrada quieta demais. Quando tá calmo demais, aí que complica!",
  288: "Bah, sempre que um velho sábio fala em ‘simples tarefa’, pode saber que vem encrenca grande pela frente!",
  289: "Por Tarastia! Nunca ignore porta trancada em lugar abandonado. Ou tem tesouro trilegal atrás, ou tem problema grande!",
  290: "Bah, Conheci um cusco que foi um gênio, resolveu cutucar o artefato brilhando roxo. Coisa brilhando roxo nunca é coisa boa!",
  291: "Por Tarastia! Se o contrato é longo demais, tem letra miúda querendo ferrar aventureiro desatento!",
  293: "Por Tarastia! Sempre pergunta quanto pagam ANTES de aceitar missão. Depois que mata dragão, eles esquecem o combinado!",
  294: "Bah, se o mago diz ‘é seguro’, bota mais uma corda, mais uma estaca e faz uma prece pra tua imortal favorita!",
  295: "Por Tarastia! Chegou em cidade estranha, pergunta primeiro onde é a taverna e onde é o templo. O resto é detalhe!",
  296: "Bah, trilha de pegada grande demais nunca termina em coisa boa. Ou é gigante, ou é bicho que come gigante!",
  297: "Por Tarastia! Se o vilão começa a discursar demais, corta no meio com aço. Falar bonito não salva de lâmina, tchê!",
  298: "Bah, inventário em dia é vida! Nada de descobrir em combate que flecha acabou ou que poção ficou na estalagem!",
  299: "Por Tarastia! Nunca vira as costas pra baú fechado. Pelo que ouvi, aqui, até móvel tem dente e mau humor!",
  300: "Bah! Se o bardo tá quieto demais, ou tá tramando ou tá com culpa. Nenhum dos dois é bom sinal!",
  301: "Por Tarastia! Quando o ladino diz ‘deixa comigo’, metade das vezes é solução, metade é problema. Mas sempre é divertido!",
  302: "Bah, já percebeste que quanto mais velha a ruína, mais ela quer nos matar? Pedra antiga tem rancor, tchê!",
  303: "Por Tarastia! Se o alquimista diz ‘não chacoalha o frasco’, é justamente o frasco que vai sacudir na mochila no primeiro tropeço!",
  304: "Bah, reunião com nobre nunca é de graça. Se tão oferecendo banquete, é porque o trabalho é pior que a comida!",
  305: "Por Tarastia! Sempre que o DM, digo, o destino, fica sorrindo demais, é porque vem armadilha daquelas pela frente!",
  306: "Bah, aprender idioma local salva vida, tchê! Já evitei briga séria só por saber quando o outro me xingou educado!",
  307: "Por Tarastia! Se o clérigo fala ‘isso não é natural’, aí sim que a gente sabe que tá encrencado até o pescoço!",
  308: "Bah, antes de atravessar ponte velha, manda o mais leve primeiro. É estratégia, não é falta de carinho!",
  309: "Por Tarastia! Nunca subestima goblin organizado. Cusco pequeno com plano vira problema grande demais!",
  310: "Bah, no fim do dia o que importa é isso: a gente volta vivo, com história trilegal pra contar e, se der, com mais ouro que ontem!"
};
 
export const Groups ={
 SUNNY:  "1",
 CLOUDY:  "2",
 RAINING:  "3",
 BY_CAMPFIRE:  "4",
 EXPLAINING_TARASTIA:  "5",
 ENTERING_BATTLE:  "6",
 GETTING_HURT:  "7",
 BELOW_FIFTY_PERCENT_HEALTH:  "8",
 BELOW_TWENTY_FIVE_PERCENT_HEALTH:  "9",
 FRIEND_GETTING_HURT:  "10",
 FRIEND_FALLING_IN_BATTLE:  "11",
 FACING_GIANT_ENEMY:  "12",
 KILLING_ENEMY:  "13",
 MISSING_ATTACK:  "14",
 ENEMY_WITH_IMMUNITY:  "15",
 ENTERING_FOREST:  "16",
 ENTERING_DARK_PLACE:  "17",
 ENTERING_GLOOMY_PLACE:  "18",
 MEETING_SOMEONE:  "19",
 INTERACTING_WITH_MINSC_AND_BOO:  "20",
 INTERACTING_WITH_MORDENKAINEN:  "21",
 ENTERING_SACRED_PLACE:  "22",
 EXPLAINING_OMBU_BUGIO_CUSCO:  "23",
 ENTERING_CITY:  "24",
 EXHAUSTED_AND_SLEEPY:  "25",
 COMPLAINING_ABOUT_GROUP:  "26",
 LEAVING_GROUP:  "27",
 BEING_DECEIVED_BY_GROUP:  "28",
 EXCESS_WEIGHT:  "29",
 FIND_SOME_PECULIAR_ITEM:  "30" ,
 RANDOM:  "999" //required this code
};

export const brizolaGroupToLines: Map<string, string> = new Map([
  ["1", "1;2;4;5;6;7;8;9;10"],
  ["2", "11;12;13;14;15;16;17;18;19;20"],
  ["3", "21;22;23;24;25;26;27;28;29;30"],
  ["4", "31;32;33;34;35;36;37;38;39;40"],
  ["5", "41;42;43;44;45;46;47;48;49;50"],
  ["6", "51;52;53;54;55;56;57;58;59"],
  ["7", "60;61;62;63;64;65;66;67;68"],
  ["8", "69;70;71;72;73;74;75;76;77"],
  ["9", "78;79;80;81;82;83;84;85;86;87"],
  ["10", "88;89;90;91;92;93;94;95;96;97"],
  ["11", "98;99;100;101;102;103;104;105;106;107"],
  ["12", "108;109;110;111;112;113;114;115;116;117"],
  ["13", "118;119;120;121;122;123;124;125;126;127"],
  ["14", "128;129;130;131;132;133;134;135;136;137"],
  ["15", "138;139;140;141;142;143;144;145;146;147"],
  ["16", "148;149;150;151;152;153;154;155;156;157"],
  ["17", "158;159;160;161;162;163;164;165;166;167"],
  ["18", "168;169;170;171;172;173;174;175;176;177;178"],
  ["19", "179;180;181;182;183;184;185;186"],
  ["20", "187;188;189;190;191;192;193;194;195;196"],
  ["21", "197;198;199;200;201;202;203;204;205;206"],
  ["22", "207;208;209;210;211;212;213;214;215;216"],
  ["23", "217;218;219;220;221"],
  ["24", "222;223;224;225;226;227;228;229;230;231"],
  ["25", "232;233;234;235;236;237;238;239;240;241;283;292"],
  ["26", "242;243;244;245;246;247;248;249;250;251"],
  ["27", "252;253;254;255;256"],
  ["28", "257;258;259;260;261"],
  ["29", "262;263;264;265;266;267;268;269;270;271"],
  ["30", "272;273;274;275;276;277;278;279;280;281"],
  ["31", "282;284;285;286;287;288;289;290;291;293;294;295;296;297;298;299;300;301;302;303;304;305;306;307;308;309;310"]
]);


 
  