 
export const minscLines:any = { 1:"Fique parado e entregue-se, para que meu hamster possa dar uma boa olhada em você!",
2:"Não, não se desespere! Eu vou te inspirar avançando com tudo!",
3:"Preciso de cura para continuar lutando!",
4:"Por favor, cuide de... Boo...",
5:"Boo gosta da florestas! E eu também. Há muito o que roer aqui.",
6:"Tanta gente com pessoas tão pequenas! Abram caminho para Minsc e Boo, pequenos!",
7:"Um covil de maldade fétida! Na verdade, essa maldade não é tão fedida quanto costuma ser. Mesmo assim viemos por você, maldade bem lavada!",
8:"Ahh, eu prefiro a luz do dia. A maldade merece ver a justiça que distribuo!",
9:"Boo dorme: embora continuemos em frente.",
10:"Aham?",
11:"Sim?",
12:"Você quer o Boo?",
13:"O quê?",
14:"Hein?",
15:"Problemas?",
16:"Primeiro vem a espada!",
17:"Menos conversa, mais luta!",
18:"Sim!",
19:"Quando o perigo chama, Minsc responde. Primeiro vem a espada !",
20:"Eu dou chutes em traseiros ruins, e não posso mentir sobre isso.",
21:"Só existe um BOO! Ha! Não aceita substitutos.",
22:"Abram caminho, maldade! Estou armado até os dentes e com um hamster!",
23:"Caiu como uma árvore poderosa!",
24:"Dynaheir! Eu falhei com você!",
25:"Isso doi, não doi, maldade ?",
26:"Um golpe e um erro!",
27:"Sem efeito? Preciso de uma espada maior.",
28:"Embora Minsc seja forte como poucos, ele não pode carregar tudo. E ele deve fazer espaço para Boo.",
29:"Minsc não tem certeza de como ele fez isto.",
30:"Ninguém me verá, embora o meu grito de batalha possa me entregar.",
31:"Espadas não falham, mas feitiços falham. Como este falhou.",
32:"O astuto Minsc prepara uma armadilha para a maldade entrar! Venham por aqui, maldade!",
33:"AHHHH! Minsc será livre! Esses laços não segurarão minha fúria! Traseiros serão generosamente chutados!",
34:"Irmandade, aventura e aço contra aço. A matéria das lendas e dos heróis! Certo, Boo?",
35:"Sim, Boo, eu concordo. Este grupo merece um puxão de moral.",
36:"Se eu continuar com isso, eu nunca mais poderei olhar Boo nos olhos. Escolha com cuidado; não deixarei isso acontecer e você não vai querer ter Minsc como inimigo, vai ? ",
37:"Você ultrapassou a linha da maldade! Prove a justiça do hamster!",
38:"Magia é impressionante, mas agora Minsc lidera! Espadas para todos!",
39:"Preciso descansar, estou com uma péssima irritação por causa da armadura.",
40:"Meu hamster está inquieto! Se somos aventureiros, vamos aventurar!",
41:"Vá direto para os olhos, Boo. VÁ PARA OLHOS! RrraaaAAGHGHH!",
42:"Preciso de ajuda em breve... para que meu hamster não fique órfão.",
43:"Boo gosta da floresta.",
44:"Maldade a cada esquina. Cuidado para não pisar em nenhuma.",
45:"Ahh, noite. Boa para se aproximar da maldade.",
46:"Quem quer um pouco?",
47:"Vocês apontam, eu soco.",
48:"Menos conversa, mais luta!",
49:"Chutando traseiros por uma boa causa!",
50:"Quem não chora não leva chute.",
51:"Armadura completa e carregando aço afiado!",
52:"Engane-me uma vez, vergonha sua; engane-me duas, cuidado! Eu sou enorme!",
53:"Quando a coisa ficar difícil, sigam meu roedor.",
54:"Há segurança em números, e eu sou dois ou três, pelo menos.",
55:"Será como você quer. É meu dever solene garantir o que você precisa.",
56:"Toque em algo que eu protejo, e para sempre você responderá ao chamado da natureza com uma boa cor vermelha na urina!",
57:"Continue tocando, bardo! É música doce para meu amigo peludo.",
58:"Se você viaja com Minsc, você se mantém na linha! Não tolerarei vagabundos enquanto estou ocupado sendo um herói!",
59:"Boo não gosta do seu jeito. Ficarei longe de você!",
60:"Escolha seus amigos sabiamente. Nem todos são tão confiáveis quanto Minsc e Boo.",
61:"Não há lugar melhor para morrer do que no campo de batalha!",
62:"Sou de poucas palavras e menos hesitações! O aviso já passou, e agora você vai morrer!",
63:"Suas palavras são tão afiadas quanto minha lâmina, embora não sejam nem metade tão brilhantes. Oooo, brilhante adoro coisas com brilho.",
64:"Não me ofendo com seus comentários. Você simplesmente não entende os laços que tenho com Boo.",
65:"Eh? Onde você nos trouxe, Boo? Estou devidamente impressionado com seu espetáculo de grandes poderes, mas um pequeno aviso teria sido bom. Não importa! Onde quer que o mal pise, Minsc pisa mais alto!",
66:"Ooo! Olhe quem você encontrou, Boo, com seu infalível senso de direção de hamster! É nosso bom amigo, <CHARNAME_TARGET_01>! Uma reunião de heróis! Que todo o mal trema diante de nós como gelatina rançosa, ha!",
67:"Todos nós somos heróis, você, Boo e eu! Hamsters e rangers em toda parte, festejem!",
68:"Esse comportamento não pode continuar! Sinta o olhar ardente do meu hamster e mude suas maneiras!",
69:"Isso não está certo. Mude nosso curso ou terei que aplicar um golpe considerável de virtude em você!",
70:"Boo só suporta até certo ponto!",
71:"Minsc liderará com lâmina e chute ! Boo que cuida dos detalhes.",
72:"Precisamos descansar em breve. Boo está ficando inquieto.",
73:"Boo precisa se exercitar",
74:"Sinta o golpe da justiça!",
75:"Divertido demais! Hehe. Certo, Boo?",
76:"Preciso de ajuda logo. Boo é muito jovem para ter que me vingar.",
77:"Você sabe... acho que a floresta gosta de Boo.",
78:"Cidades sempre estão repletas de mal e decadência. Vamos dar uma boa sacudida e ver o que cai!",
79:"Uma toca de mal fedido. Cubra o nariz, Boo. Não deixaremos nenhuma fenda sem investigar!",
80:"Coisas estranhas se movem à noite, mas nenhuma se move mais do que Minsc!",
81:"Espadas, não palavras!",
82:"Minsc e Boo estão prontos.",
83:"Cada hamster tem seu dia.",
84:"Armado, afiado e pronto para agir.",
85:"Boo diz, \"O quê?!\"",
86:"Onde Minsc vai, o mal se afasta.",
87:"Salte pra cima da minha espada enquanto pode, mal. Não serei tão gentil!",
88:"Viva pela espada, viva por muito tempo!",
89:"Afaste-se para a justiça!",
90:"Vê a batalha, Boo? Corra, Boo, corra!",
91:"Dê passagem, vilania! Herói a caminho!",
92:"Quanto maiores, mais forte eu bato!",
93:"Não ensine meu hamster a rezar a missa!",
94:"Ah não!",
95:"Ah, isso não está certo!",
96:"Virei para proteger Boo e perdi meu feitiço. NÃO estou arrependido.",
97:"Tive que largar o que você me deu. Tenho apenas dois braços e não tenho mais espaço.",
98:"Aiii!",
99:"Arght!",
100:"Uiii!" ,
101:"Boo não é um rato, ele é uma miniatura de um Hamster Espacial Gigante. Não o ofenda! Para que ele não roa suas orelhas enquanto você dorme!" ,
102:"Ohh, você é esperto mesmo! Agora estou entendendo."  
};

export const minscGroupToLines:Map<string,string> = new Map([ 
  ["1","1"],
  ["2","2;16;17;19;22;38;41;46;47;48;49;50;61;62;74;81;87;89;90;91;20;54"],
  ["3","42;76;98;99;100"],
  ["4","5;43;77"],
  ["5","6;78;44"],
  ["6","7;44;79"],
  ["7","12"],
  ["8","85;13;10;11"],
  ["9","15;56"],
  ["10","92"],
  ["11","18;55"],
  ["12","70;95;94"],
  ["13","23"],
  ["14","25;22;38;46;49;50;74"],
  ["15","26"], 
  ["17","28;97"],
  ["18","29"],
  ["19","32"],
  ["20","33"],
  ["21","39;72"],
  ["24","8"],
  ["23","80"],
  ["25","51"],
  ["26","52"],
  ["27","94"],
  ["28","57"],
  ["29","58"],
  ["30","59"],
  ["31","63;102"],  
  ["34","93"],
  ["35","96"],
  ["38","10;11;14"],
  ["41","32"],
  ["37","9;20;21;24;34;40;53;60;65;67;71;73;75;83;86;88"],
  ["1;32","66"],
  ["2;3;36","3;4"],
  ["2;16","27"],
  ["2;39","30"],
  ["2;10","92"], 
  ["3;36","3;4"],
  ["2;3","3;4;42;76"],
  ["2;3;22","42;76"],
  ["2;3;36","3;4"],
  ["3;22","42;76"], 
  ["12;40","31"],
  ["12;42","35;36;68;69;24"],
  ["12;44","37"],
  ["12;47","64;101"],
  ["999","82;84"]
]);
 
export const Groups = {
    FIND_SOMEONE: "1",
    ENTER_IN_BATTLE: "2",
    GETTING_HURT: "3",
    IN_FOREST: "4",
    IN_CITY: "5",
    IN_DUNGEON: "6",
    IF_SOMEONE_ASKS_TO_CATCH_THE_BOO: "7",
    I_DONT_UNDERSTAND_SOMTHING: "8",
    IF_SOMEONE_HURTS_A_GROUP_MEMBER: "9",
    BIG_ENEMY: "10",
    AGREEING_WITH_THE_GROUP: "11",
    COMPLAINING_ABOUT_THE_GROUP: "12",
    KILLING_AN_ENEMY: "13",
    LANDING_A_HIT: "14",
    MISSING_THE_HIT: "15",
    ENEMY_WITH_IMMUNITY: "16",
    OVERWEIGHT: "17",
    AFTER_SOMEONE_CASTS_MAGIC: "18",
    SETTING_AN_AMBUSH: "19",
    BREAKING_FREE_FROM_MAGIC: "20",
    WITH_EXHAUSTION: "21",
    HALF_LIFE: "22",
    DURING_NIGHT: "23",
    DURING_DAY: "24",
    FULL_ARMOR: "25",
    ON_BEING_DECEIVED: "26",
    TO_THE_BARD: "28",
    JOINING_THE_GROUP: "29",
    LEAVING_THE_GROUP: "30",
    PRAISING_THE_SPEECH: "31",
    FIND_SOMEONE_FAMILIAR: "32",
    COMPLAINING_ABOUT_RECEIVING_ORDERS: "34",
    I_AM_READY: "33",
    LOSING_INVISIBILITY_MAGIC: "35",
    ONE_QUARTER_LIFE: "36",
    NOT_AGREEING_WITH_SOMETHING: "38",
    STEALTHY: "39",
    SETTING_A_TRAP: "41",
    LOWERING_MORALE: "42",
    ZERO_MORALE: "44",
    RANDOM_GROUP: "999"
} as const;
 